#Name : Abdulrehman Khan
#Roll No: PIAIC92274
#Batch: 07


In [ ]:
import numpy as af
af.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
af.add(4,8)

12

In [ ]:
af.subtract(45,30)

15

In [ ]:
af.multiply(5,12)

60

In [ ]:
af.ones((5,7),dtype=float)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
af.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
af.arange(3,5,15)

array([3])

In [ ]:
af.full((6,4),88)

array([[88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88]])

In [ ]:
af.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [ ]:
af.random.random((2,8))


array([[0.28364184, 0.37043732, 0.43506048, 0.94140074, 0.53009276,
        0.6009485 , 0.20214234, 0.09596796],
       [0.70041076, 0.87863733, 0.88730876, 0.76999999, 0.42741678,
        0.22914217, 0.74274042, 0.69958682]])

In [ ]:
af.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
af.empty(5)

array([0., 0., 0., 0., 0.])

In [ ]:
xyz=af.random.randint(0,10,(2,2))
xyz

array([[2, 8],
       [4, 2]])

In [ ]:
abc=af.eye(8)

In [ ]:
af.shape(abc)

(8, 8)

In [ ]:
af.size(abc)

64

In [ ]:
abc.dtype

dtype('float64')

In [ ]:
abc.data

In [ ]:
abc.ndim

2

In [ ]:
abc.itemsize

8

In [ ]:
abc.mean()

0.125

In [ ]:
abc.sum()

8.0

In [ ]:
af.exp(abc)

array([[2.71828183, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 2.71828183, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 2.71828183, 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 2.71828183, 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 2.71828183,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        2.71828183, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 2.71828183, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 2.71828183]])

In [ ]:
af.abs(abc)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
acd=4
acd

4

In [ ]:
abc.ravel()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [ ]:
af.pi

3.141592653589793

In [ ]:
af.sin(acd)

-0.7568024953079282

In [ ]:
af.cos(abc)

array([[0.54030231, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 0.54030231, 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 0.54030231,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.54030231]])

In [ ]:
af.cos(acd)

-0.6536436208636119

In [ ]:
af.tan(acd)

1.1578212823495775

In [ ]:
af.arcsin(0.8)

0.9272952180016123

In [ ]:
af.log(acd)

1.3862943611198906

In [ ]:
af.log2(acd)

2.0

In [ ]:
af.log10(acd)

0.6020599913279624

In [ ]:
af.add.reduce(acd)

4

In [ ]:
af.add.reduce(abc)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
af.multiply.reduce(acd)

4

In [ ]:
af.multiply.accumulate(abc)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
af.hsplit(de,3)

[array([[7],
        [2],
        [3]]),
 array([[6],
        [2],
        [4]]),
 array([[5],
        [7],
        [9]])]

In [ ]:
de=af.random.randint(0,10,(3,3))
de

array([[7, 6, 5],
       [2, 2, 7],
       [3, 4, 9]])

In [ ]:
af.power(4,6)

4096

In [ ]:
af.power(2,8)

256

In [ ]:
# horizontal splitting
af.hsplit(de,3)

[array([[7],
        [2],
        [3]]),
 array([[6],
        [2],
        [4]]),
 array([[5],
        [7],
        [9]])]

In [ ]:
# Vertical splitting
af.vsplit(de,3)

[array([[7, 6, 5]]), array([[2, 2, 7]]), array([[3, 4, 9]])]

In [ ]:
af.prod(de)

635040

In [ ]:
af.std(de)

2.309401076758503

In [ ]:
af.var(de)

5.333333333333333

In [ ]:
ab= af.array([1,2,3,2,3,4,3,4,5,6])
ba = af.array([7,2,10,2,7,4,9,4,9,8])
af.unique((ab,ba))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
names = af.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = af.random.randn(7, 4)
data[names=="Bob"]

array([[ 1.24440279, -1.34066938, -0.31962772,  0.53765665],
       [ 0.69269568, -1.01319227,  0.61175013,  0.80120306]])

In [ ]:
gh=af.arange(1,16).reshape(5,3)
gh

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
xd = af.array([[1., 2., 3.], [4., 5., 6.]])
yd = af.array([[6., 23.], [-1, 7], [8, 9]])
af.dot(xd,yd)

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
ad=af.random.gamma((5,6))
print(ad)
print('\n',ad.mean())

[4.75170116 3.4171311 ]

 4.08441613065613


In [ ]:
af.median(ad)

4.08441613065613

In [ ]:
af.transpose(ad)

array([4.75170116, 3.4171311 ])

In [ ]:
print(af.linalg.det(abc))
print(af.linalg.det([[3,4],[5,6]]))

1.0
-1.9999999999999971


In [ ]:
abc

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
af.percentile(acd,8)

4.0